sudo: required
dist: trusty
language: cpp

addons:
  apt:
    packages:
      - libxml++2.6-dev
      - libarchive-dev

script:
  - autoreconf -fi
  - ./configure --disable-static --enable-zhfst
  - make -j3
  - make -j1 check
